#!/bin/bash

PS3="Scegli un valore: "

if ! [ $# = 1 ]; then
	echo "Usage: try with \"bash $0 sysCallsFile\""
	echo "sysCallsFile --> file name"
else
	echo
	echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	echo
	if grep sysCalls $1; then
		echo
		echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		echo
		select sel in {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,100,101,102,103}; do
			bash search.sh $1 $sel
		done
	fi
fi
